"""add users table

Revision ID: 0dca52b0bd25
Revises: 5c67a2a8ab86
Create Date: 2026-06-30 19:45:54.406753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dca52b0bd25'
down_revision: Union[str, Sequence[str], None] = '5c67a2a8ab86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('Email_id', sa.String(), nullable=False),
    sa.Column('User_name', sa.String(), nullable=False),
    sa.Column('Password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Email_id'),
    sa.UniqueConstraint('User_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
